version: '2'
services:
  gateway:    
    image: aksenchyk/fm-200loc:build
    environment:      
      - REDIS_HOST=redis
      - HTTP_PORT=5601         
    depends_on:      
      - redis    
    entrypoint: ./wait-for-it.sh redis:6379 dashboard:5601 -s -- npm start
  dashboard:
    image: aksenchyk/fm-dashboard:build
    environment: 
      - REDIS_HOST=redis
    command: npm start -- p 5601
  redis:    
    image: redis:latest 